- main/createViolinPlot.js
- main/index.html
Violin plot is now able to be viewed on homepage.
createViolinPlot.js added to main folder
> Added Violin Plot

- main/fetchCohortData.js
- main/getCohortDescriptions.js
- main/getCohortIDs.js
- main/index.html
- Created JS files for obtaining cohort metadata from Firebrowse (fetchCohortData.js, getCohortIDs.js, getCohortDescriptions.js); however, these files are not used yet, as cohort metadata for cohort selection is still hard-coded
- Removed boxplot tab
> Cleaned layout

- main/index.html
- main/style.css
- Added placeholder for cancer type select, which disappears once an option is selected
- Modified gene input bar
- Renamed placeholder to be more specific ("Enter List of Genes Here --> "Enter Gene ID(s)")
- Decreased width to 50% to match select bar
- Matched placeholder styling with that of cancer type select
> Improved select/input styling

- main/docManipulation.js
- main/index.html
- main/style.css
Styled button to be centered, fixed tabs, enlarged and organized violin plot, added dynamic select boxes.
> Presentation impress js

- main/style.css
Changed font color of tabs so that it matches color of header.
> Change font color of tabs

- README.md
> update readme entry for rmoffitt

- main/css/style.css
- main/html/about.html
- main/html/index.html
- main/js/dataAcquisition/getCohortDescriptions.js
- main/js/dataAcquisition/getCohortIDs.js
- main/js/dataAcquisition/getExpressionValuesOnly.js
- main/js/docManipulation.js
- main/js/fillSelectBoxes.js
- main/js/plots/createHeatmap.js
Tidied code and fixed minor bugs
> Refactoring

- main/js/docManipulation.js
Added buttons to each violin plot so that they can be faceted separately. These are just for testing. Will most likely be replaced with a drop-down of some kind in the future.
> Violin Buttons

- main/js/plots/createHeatmap.js
Fixed this so it doesn't slow down by clustering immediately when opening heatmap for a large cohort. Would also recommend making the default cohort not BRCA+SARC, something smaller
> Heatmap - added checkbox for clustering, update plot button, default sort by mean expression

- main/html/index.html
- main/js/fillSelectBoxes.js
- main/js/plots/dataExploration.js
- Deletion of selected clinical feature also deletes that plot
> Fix bugs in clinical feature selection

- main/html/index.html
Libs should load in correctly now. Also the new css that is loaded in causes issues (violin plot tooltip disappered)
> fixed urls for libs

- main/html/index.html
- main/js/afterSubmit.js
- main/js/dataAcquisition/fetchClinicalData.js
- main/js/dataAcquisition/getClinicalDataJSONarray.js
- main/js/plots/createHeatmap.js
Updated the code to pull clinical data using the user-selected query options (from clinicalQuerySelectBox) and also pulls using the fetchClinicalData_bc or _cc command depending on if intersecting barcodes exist. Also fixed plot issue where tooltip was overlapping the sample track legend
> Heatmap updates: clinical data querying from user selections, barcode/cohort, tooltip error fix

- main/html/index.html
- Not used by our app
- It was altering our preexisting css
> Remove bootstrap libs

- main/css/style.css
- main/html/index.html
- main/js/afterSubmit.js
Downloads data in JSON format as an array of 3 objects including header describing data/cohort/queries, expressionData, and clinicalData
Some details need to be added, including information on the filter steps (pie chart slices selected)
CSV download functionality in progress
> Download data: implemented JSON download functionality

- main/html/index.html
- main/js/fillSelectBoxes.js
- fillFirstGeneSelectBox()
- fillSecondGeneSelectBox()
- The above 2 functions are replaced by fillGeneSelectBoxes()
> Delete unused functions

- main/html/index.html
- main/js/afterSubmit.js
- main/js/dataAcquisition/fetchClinicalData.js
- main/js/dataAcquisition/fetchExpressionData.js
- main/js/dataAcquisition/getClinicalDataJSONarray.js
- main/js/dataAcquisition/getDataFromSelectedPieSectors.js
- main/js/dataAcquisition/getExpressionDataJSONarray.js
- main/js/fillSelectBoxes.js
- i.e., For retrieval of Clinical_FH and mRNASeq data from Firebrowse
- Now, using functions defined in [episphere/firebrowse repo](https://github.com/episphere/firebrowse/blob/master/firebrowse.js)
- These new functions will allow retrieval of larger quantities of data, if that is what is requested by the user
> Update functions for data retrieval

- main/css/style.css
- main/html/index.html
- main/js/afterSubmit.js
Let me know if that works. The text cuts out with very small screen sizes but I don't think our target user base will have a problem with that.
> Styling of buttons

- main/js/plots/createPieCharts.js
Checks all data instead of just the first and second elements for digits.
> Dynamic checking for continuous data

- main/js/fillSelectBoxes.js
> Display previous selections saved in localStoarge

- main/js/plots/createPieCharts.js
- Add gap between bars in histograms
- Add label to histogram hover tooltip: "Number of samples:"
> Continuous data chart styling

- main/js/plots/createPieCharts.js
> Correct conditions for generation of histograms

- main/js/afterSubmit.js
- main/js/plots/createViolinPlot.js
The size of the violin plots have been reduced to roughly 50% the original width and 75% the original height.
> Resized violin to take up half of screen width

- main/js/afterSubmit.js
- main/js/plots/createViolinPlot.js
The violin plots are now all partitioned by a single selector box.
> Single violin partition select

- main/js/fillSelectBoxes.js
- main/js/plots/createPieCharts.js
clinicalType array that contains all clinical features for the selected cohort(s). For each feature, it has a name, type (continuous or categorical), and isSelected (true or false). This array is global so the heatmaps should be able to access it.
> clinicalType array for heatmaps

- main/html/about.html
- main/html/index.html
- Temporarily commented image tab
- Updated list of contributors
> Update html pages

- main/js/plots/createHeatmap.js
Fixed sample track legend to adjust size to fit depending on maximum height of all categorical and continuous variables, and column width adjusts correctly as well.
Modified sample track colors to green/white/orange (can change later for different colors)
Also changed clustering option to a toggle button (similar to violin) and styled update heatmap button.
>  Heatmap updates: mostly aesthetics

- main/css/style.css
- main/html/index.html
- main/js/afterSubmit.js
- main/js/dataAcquisition/getDataFromSelectedPieSectors.js
- Loader no longer erroneously overlays components of app
- Changed loader position from absolute to relative
> Fix positioning of loader

- main/html/about.html
fixes https://github.com/web4bio/webgen/issues/297
> remove docManipulation.js because it doesn't exist

- main/js/afterSubmit.js
- main/js/dataAcquisition/getDataFromSelectedPieSectors.js
this pr proposes adding user input validation. when the submit button is clicked, the app validates that at least one tumor type has been chosen and that at least one gene has been chosen. if not, a popup window appears to alert the user.
fixes https://github.com/web4bio/webgen/issues/304
> fix: validate user inputs on submit

- main/js/fillSelectBoxes.js
- These changes remove uninformative errors from appearing in console
- onchange functions for tumor type select box only proceed if there is a tumor type selection
> Add check for tumor type selection

- main/js/plots/createViolinPlot.js
modified the violin plot x-axis labels to be on 45 degree slant
> vplot x-axis modified

- main/js/state.js
the purpose of this pull request is to implement the state object that we will use to store/update app state.
closes #353 
replaces #356
> add state.js to hold state of app

- main/js/plots/createViolinPlot.js
Resolved issue where violin plots were not building.
> Resolved issues preventing violin plots from being rendered.

- main/html/index.html
- main/js/smartCache/main.js
* Stores rnaSeq data as a matrix of objects (keys are cohort and gene expr)
* Calculates the diff and retrieves the existing data from IndexedDB, else fetches and stores
* Global object called **cacheMe**
* Get and forget by calling **cacheMe.fetchWrapper(...)** -> 1-d array of objects
> Smart Caching of HTTP Requests

- main/js/dataAcquisition/fetch.js
I replaced the url for Issue #383.
> herokuapp-replacement

- main/js/smartCache/main.js
Ensures that the data is loaded in before initializing the CacheInterface object
> Fix a small bug with CacheInterface object

- main/js/afterSubmit.js
- main/js/dataAcquisition/fetch.js
- main/js/dataAcquisition/getDataFromSelectedPieSectors.js
- main/js/fillSelectBoxes.js
- main/js/plots/createViolinPlot.js
The web app now fetches all the clinical data for a specific cohort combination by using a page number parameter.
> firebrowse.fetchClinicalFH Queries All Clinical Data

- main/js/plots/createPieCharts.js
Histograms were previously only displaying number of unique values (each value had a frequency of 1); histograms now display unique values against their true frequencies.
> Histograms now properly display results

- main/css/style.css
- main/html/index.html
- main/js/afterSubmit.js
- main/js/dataAcquisition/fetch.js
- main/js/fillSelectBoxes.js
- main/js/progressBar.js
Merging progress bar and resolved CORS fetch issue fix.
> Adit release testing

- main/html/index.html
- main/js/fillSelectBoxes.js
- Deletes outdated commented code
- Reorders function calls in index.html based on which dropdowns should be rendered first
- Updates URLs to gene list and gene pathways list JSON files so that they always correspond to proper app version
- Selectively excludes 'cohort' as a field in the clinical feature dropdown. Prior to this, we were excluding the first field in the clinical data returned from firebrowse under the assumption that 'cohort' would always be the field at index 0 (which is not always true). Again, we want to exclude 'cohort' from appearing in the dropdown because the selected 'cohort' is obvious to the user based on the tumor type select box
> Housekeeping
